import { inject, Injectable } from "@angular/core";
import { ActivityLog } from "../Model/ActivityLog";
import { HttpClient } from "@angular/common/http";
import { catchError, map, Observable, throwError } from "rxjs";


@Injectable({
    providedIn: 'root'
})
export class ActivityLogService {
    activityLog: ActivityLog;

    http : HttpClient = inject(HttpClient);

    dataBaseUrl = `https://final-assessment-1-default-rtdb.asia-southeast1.firebasedatabase.app`;


    getAllActivity(): Observable<{ [key: string]: ActivityLog }> {
        return this.http.get<{ [key: string]: ActivityLog }>(`${this.dataBaseUrl}/activityLogs.json`).pipe(
          map(response => {
            return response;
          })
        );
      }

      //activity logs adding
      addActivityLog(logData: ActivityLog) {      
        // Use POST to save logs directly under 'activityLogs' with a unique key generated by Firebase
        this.http.post(`${this.dataBaseUrl}/activityLogs.json`, logData)
          .subscribe({
            next: () => console.log('Activity logged successfully'),
            error: (error) => console.error('Error logging activity:', error)
          });
      }
      
      

  

  
}